import { describe, it, expect } from 'vitest';
import { parseYarnClassic, parseYarnBerry } from '../../src/providers/node/parsers/yarn-lock.js';

describe('parseYarnClassic', () => {
  it('parses yarn classic lockfile format', () => {
    const lockContent = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

express@^4.18.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"
  integrity sha512-5/PsL6iGPdfQ/lKM1UuielYgv3BUoJfz1aUwU9vHZ+J7gyvwdQXFEBIEIaxeGf0GIcreATNyBExtalisDbuMqQ==
  dependencies:
    accepts "~1.3.8"

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-Al2iSNDduwecsq8kZJgg1Z7aMq0F8BDBw8FSfnqibgFShnSvgG+vYcHjltu3TjzfdcTRdFoADFd7+ld7ykSDaw==

accepts@~1.3.8:
  version "1.3.8"
  resolved "https://registry.yarnpkg.com/accepts/-/accepts-1.3.8.tgz"
  integrity sha512-PYAthTa2m2VKxuvSc3gualQEzF6OQRz6HCbU/xFFpYNYleco0J2Y5pugIleHF0kGzsa8MnbAPIWxLdnUA2hRlg==
`;

    const result = parseYarnClassic(lockContent);

    expect(result.length).toBeGreaterThanOrEqual(3);
    expect(result).toContainEqual({
      name: 'express',
      version: '4.18.2',
      ecosystem: 'npm',
    });
    expect(result).toContainEqual({
      name: 'lodash',
      version: '4.17.21',
      ecosystem: 'npm',
    });
    expect(result).toContainEqual({
      name: 'accepts',
      version: '1.3.8',
      ecosystem: 'npm',
    });
  });

  it('handles scoped packages', () => {
    const lockContent = `# yarn lockfile v1

"@types/node@^20.10.0":
  version "20.10.0"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-20.10.0.tgz"

"@types/express@^4.17.21":
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/@types/express/-/express-4.17.21.tgz"
`;

    const result = parseYarnClassic(lockContent);

    expect(result).toContainEqual({
      name: '@types/node',
      version: '20.10.0',
      ecosystem: 'npm',
    });
    expect(result).toContainEqual({
      name: '@types/express',
      version: '4.17.21',
      ecosystem: 'npm',
    });
  });

  it('handles resolution field', () => {
    const lockContent = `# yarn lockfile v1

package@^1.0.0:
  version "1.2.3"
  resolved "https://registry.yarnpkg.com/package/-/package-1.2.3.tgz"
`;

    const result = parseYarnClassic(lockContent);

    expect(result).toContainEqual({
      name: 'package',
      version: '1.2.3',
      ecosystem: 'npm',
    });
  });

  it('handles checksum field', () => {
    const lockContent = `# yarn lockfile v1

express@^4.18.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"
  integrity sha512-5/PsL6iGPdfQ/lKM1UuielYgv3BUoJfz1aUwU9vHZ+J7gyvwdQXFEBIEIaxeGf0GIcreATNyBExtalisDbuMqQ==
`;

    const result = parseYarnClassic(lockContent);

    expect(result.length).toBeGreaterThanOrEqual(1);
    expect(result.some((d) => d.name === 'express' && d.version === '4.18.2')).toBe(true);
  });

  it('handles empty lockfile', () => {
    const lockContent = `# yarn lockfile v1
`;

    const result = parseYarnClassic(lockContent);

    expect(result).toHaveLength(0);
  });
});

describe('parseYarnBerry', () => {
  it('parses yarn berry lockfile format', () => {
    const lockContent = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

express@npm:^4.18.0:
  version: 4.18.2
  resolution: "express@npm:4.18.2"
  checksum: 10/express-4.18.2.tgz#sha512-abc123

lodash@npm:^4.17.21:
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10/lodash-4.17.21.tgz#sha512-def456

accepts@npm:~1.3.8:
  version: 1.3.8
  resolution: "accepts@npm:1.3.8"
  checksum: 10/accepts-1.3.8.tgz#sha512-ghi789
`;

    const result = parseYarnBerry(lockContent);

    expect(result.length).toBeGreaterThanOrEqual(3);
    expect(result).toContainEqual({
      name: 'express',
      version: '4.18.2',
      ecosystem: 'npm',
    });
    expect(result).toContainEqual({
      name: 'lodash',
      version: '4.17.21',
      ecosystem: 'npm',
    });
    expect(result).toContainEqual({
      name: 'accepts',
      version: '1.3.8',
      ecosystem: 'npm',
    });
  });

  it('handles scoped packages', () => {
    const lockContent = `__metadata:
  version: 8

"@types/node@npm:^20.10.0":
  version: 20.10.0
  resolution: "@types/node@npm:20.10.0"

"@types/express@npm:^4.17.21":
  version: 4.17.21
  resolution: "@types/express@npm:4.17.21"
`;

    const result = parseYarnBerry(lockContent);

    expect(result).toContainEqual({
      name: '@types/node',
      version: '20.10.0',
      ecosystem: 'npm',
    });
    expect(result).toContainEqual({
      name: '@types/express',
      version: '4.17.21',
      ecosystem: 'npm',
    });
  });

  it('skips metadata section', () => {
    const lockContent = `__metadata:
  version: 8
  cacheKey: 10c0

express@npm:^4.18.0:
  version: 4.18.2
`;

    const result = parseYarnBerry(lockContent);

    expect(result).toContainEqual({
      name: 'express',
      version: '4.18.2',
      ecosystem: 'npm',
    });
    expect(result.some((d) => d.name === '__metadata')).toBe(false);
  });

  it('handles resolution field', () => {
    const lockContent = `__metadata:
  version: 8

package@npm:^1.0.0:
  version: 1.2.3
  resolution: "package@npm:1.2.3"
`;

    const result = parseYarnBerry(lockContent);

    expect(result).toContainEqual({
      name: 'package',
      version: '1.2.3',
      ecosystem: 'npm',
    });
  });

  it('handles empty lockfile', () => {
    const lockContent = `__metadata:
  version: 8
`;

    const result = parseYarnBerry(lockContent);

    expect(result).toHaveLength(0);
  });

  it('handles malformed YAML gracefully', () => {
    expect(() => parseYarnBerry('invalid: yaml: : :')).toThrow();
  });
});

