import { describe, it, expect } from 'vitest';
import { gatherDependencies } from '../src/utils/dependencies.js';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

describe('lockfile parsing integration', () => {
  it('parses npm package-lock.json for resolved versions', async () => {
    const tmpDir = mkdtempSync(join(tmpdir(), 'test-npm-'));

    try {
      // Write package.json
      writeFileSync(
        join(tmpDir, 'package.json'),
        JSON.stringify({
          dependencies: { lodash: '^4.17.21' },
          devDependencies: { vitest: '^1.0.0' },
        })
      );

      // Write package-lock.json
      writeFileSync(
        join(tmpDir, 'package-lock.json'),
        JSON.stringify({
          lockfileVersion: 3,
          packages: {
            '': {
              dependencies: { lodash: '^4.17.21' },
              devDependencies: { vitest: '^1.0.0' },
            },
            'node_modules/lodash': {
              version: '4.17.21',
              resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz',
            },
            'node_modules/vitest': {
              version: '1.0.5',
              dev: true,
            },
          },
        })
      );

      const deps = await gatherDependencies(tmpDir, { includeDev: false });

      expect(deps).toHaveLength(1);
      expect(deps[0].name).toBe('lodash');
      expect(deps[0].version).toBe('4.17.21'); // Resolved version, not ^4.17.21
      expect(deps[0].ecosystem).toBe('npm');
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it('includes devDependencies from npm lockfile when flag is set', async () => {
    const tmpDir = mkdtempSync(join(tmpdir(), 'test-npm-dev-'));

    try {
      writeFileSync(
        join(tmpDir, 'package.json'),
        JSON.stringify({
          dependencies: { lodash: '^4.17.21' },
          devDependencies: { vitest: '^1.0.0' },
        })
      );

      writeFileSync(
        join(tmpDir, 'package-lock.json'),
        JSON.stringify({
          lockfileVersion: 3,
          packages: {
            '': {
              dependencies: { lodash: '^4.17.21' },
              devDependencies: { vitest: '^1.0.0' },
            },
            'node_modules/lodash': {
              version: '4.17.21',
            },
            'node_modules/vitest': {
              version: '1.0.5',
              dev: true,
            },
          },
        })
      );

      const deps = await gatherDependencies(tmpDir, { includeDev: true });

      expect(deps).toHaveLength(2);
      expect(deps.find((d) => d.name === 'lodash')?.version).toBe('4.17.21');
      expect(deps.find((d) => d.name === 'vitest')?.version).toBe('1.0.5');
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it('parses yarn.lock for resolved versions', async () => {
    const tmpDir = mkdtempSync(join(tmpdir(), 'test-yarn-'));

    try {
      writeFileSync(
        join(tmpDir, 'package.json'),
        JSON.stringify({
          dependencies: { lodash: '^4.17.21' },
        })
      );

      writeFileSync(
        join(tmpDir, 'yarn.lock'),
        `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==
`
      );

      const deps = await gatherDependencies(tmpDir, { includeDev: false });

      expect(deps).toHaveLength(1);
      expect(deps[0].name).toBe('lodash');
      expect(deps[0].version).toBe('4.17.21'); // Resolved version
      expect(deps[0].ecosystem).toBe('npm');
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it('parses pnpm-lock.yaml for resolved versions', async () => {
    const tmpDir = mkdtempSync(join(tmpdir(), 'test-pnpm-'));

    try {
      writeFileSync(
        join(tmpDir, 'package.json'),
        JSON.stringify({
          dependencies: { lodash: '^4.17.21' },
        })
      );

      writeFileSync(
        join(tmpDir, 'pnpm-lock.yaml'),
        `lockfileVersion: '9.0'

importers:
  .:
    dependencies:
      lodash:
        specifier: ^4.17.21
        version: 4.17.21

packages:
  lodash@4.17.21:
    resolution: {integrity: sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==}
`
      );

      const deps = await gatherDependencies(tmpDir, { includeDev: false });

      expect(deps).toHaveLength(1);
      expect(deps[0].name).toBe('lodash');
      expect(deps[0].version).toBe('4.17.21'); // Resolved version
      expect(deps[0].ecosystem).toBe('npm');
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it('handles scoped packages in yarn.lock', async () => {
    const tmpDir = mkdtempSync(join(tmpdir(), 'test-yarn-scoped-'));

    try {
      writeFileSync(
        join(tmpDir, 'package.json'),
        JSON.stringify({
          dependencies: { '@babel/core': '^7.24.0' },
        })
      );

      writeFileSync(
        join(tmpDir, 'yarn.lock'),
        `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@babel/core@^7.24.0":
  version "7.24.5"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.5.tgz"
  integrity sha512-abcdefg123456
`
      );

      const deps = await gatherDependencies(tmpDir, { includeDev: false });

      expect(deps).toHaveLength(1);
      expect(deps[0].name).toBe('@babel/core');
      expect(deps[0].version).toBe('7.24.5'); // Resolved version
      expect(deps[0].ecosystem).toBe('npm');
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});

